# Generated by Django 5.0.7 on 2024-07-19 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carmodel')),
            ],
        ),
    ]
