# Generated by Django 5.0.7 on 2024-07-19 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.pricing'),
        ),
    ]
